// Resolucion Practica Clase 5
def COUNT

pipeline {
        agent any
        parameters {
            string(name: 'Palabra',defaultValue: '',description: 'Ingresa upalabra a buscar')
            string(name:'httpCode' , defaultValue: '', description: 'Ingrese http a buscar')
        }

       
        
        stages {
            stage('Descargar Logs'){
                steps {
                        //ingresar URL que se tiene que Descargar!!!!
                        sh 'curl -o /tmp/logsfiles.logs https://raw.githubusercontent.com/elastic/examples/master/Common%20Data%20Formats/apache_logs/apache_log'
                        sh 'ls-lah'
                    }
                }
                stage ('Contar lineas'){
                    steps {
                        script{
                            

                            COUNT = sh (script: "grep -c '${params.Palabra}.*${params.httpCode}' /tmp/logfiles.log", returnStdout: true).trim()
                            echo "La cantidad de lineas encontradas es: ${COUNT}"


                        }
                    }
                }
            }

        }




