// Resolucion Desafio1
def COUNT


pipeline {
        agent any
   

       
        
        stages {
            stage('Input'){
                steps {

                    script{
                        userInput=Input(
                        parameters:[
                        string(name: 'Nombre',defaultValue: '',description: 'Ingresa su Nombre'),
                        string(name: 'Apellido',defaultValue: '',description: 'Ingresa su Apellido'),
                        choice(name: 'Departamento', choices: ['Contabilidad','Finanzas','Tecnologia'], description: 'Selecciona el departamento')

                        ])
                    }

                        
                    }
                }

                stage('Passtemporal'){
                    steps{
                        script{
                            def nombre = userInput['Nombre']
                            def apellido = userInput['Apellido']
                            def PassTemp = nombre.ToLowerCase()+apellido.ToLowerCase()
                            env.TEMPORAL_PASSWORD = PassTemp
                        }
                    }
                }
                stage('Creacion del Usuario'){
                    steps {
                        script{
                            def nombre = userInput['Nombre'].ToLowerCase()
                            def apellildo = userInput['Apellido'].ToLowerCase()
                            def departamento = userInput['Departamento']
                            def TemporalPass = env.TEMPORAL_PASSWORD

                        }
                    }
                }
            }

        }




